<div id="sliderControls" style="position: relative; top: 0px; left: 0; z-index: 40">
	<table width="100%"><tbody><tr>
		<td width="90%">&nbsp;</td>
		<td><a href='#' onClick='superdashboard.slider.showPrevious()'>&lt;&lt;</a></td>
		<td><div id="startStopSlider"><a href='#' onClick='superdashboard.slider.startSlider(5000);'>Auto</a></div></td>
		<td><div id="sliderCount">0/0</div></td>
		<td width="10%"><a href='#' onClick='superdashboard.slider.showNext()'>&gt;&gt;</a></td>
	</tr></tbody></table>
</div>